name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    name: Build and Publish

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.26
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          store_path=$(pnpm store path | tr '\n' ' ')
          echo "STORE_PATH=$store_path" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm prebuild
          pnpm build

      - uses: actions/upload-artifact@v3
        with:
          name: ComfyBox-dist
          path: dist/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
